### ISSUE TITLE
Kin Error: Unhandled: undefined

### ISSUE THREAD

**Issue by MicoDan** [kin-lang/kin#109]
I encountered an error "Unhandled: undefined" while implementing the quick sort algorithm in Kin Lang. Here is the code snippet that produces the error:

```
reka urutonde_rwi_imibare = [34, 56, 23, 45, 34, 57]

porogaramu_ntoya igabanye(urutonde_rwi_imibare, hasi, hejuru) {
  reka pivot = urutonde_rwi_imibare[hejuru]
  reka i = hasi - 1

  reka j = hasi
  subiramo_niba(j < hejuru) {
    niba(urutonde_rwi_imibare[j] <= pivot) {
      i = i + 1
      reka ububiko_bwagateganyo = urutonde_rwi_imibare[i]
      urutonde_rwi_imibare[i] = urutonde_rwi_imibare[j]
      urutonde_rwi_imibare[j] = ububiko_bwagateganyo
    }
    j = j + 1
  }
  reka ububiko_bwagateganyo = urutonde_rwi_imibare[i + 1]
  urutonde_rwi_imibare[i + 1] = urutonde_rwi_imibare[hejuru]
  urutonde_rwi_imibare[hejuru] = ububiko_bwagateganyo
  garura i + 1
}

porogaramu_ntoya quick_sort(urutonde_rwi_imibare, hasi, hejuru) {
  niba(hasi < hejuru) {
    reka pivot_index = igabanye(urutonde_rwi_imibare, hasi, hejuru)
    quick_sort(urutonde_rwi_imibare, hasi, pivot_index - 1)
    quick_sort(urutonde_rwi_imibare, pivot_index + 1, hejuru)
  }
}

reka hasi = 0
reka hejuru = KIN_URUTONDE.ingano(urutonde_rwi_imibare) - 1
quick_sort(urutonde_rwi_imibare, hasi, hejuru)

reka i = 0
subiramo_niba(i < KIN_URUTONDE.ingano(urutonde_rwi_imibare)) {
  tangaza_amakuru(urutonde_rwi_imibare[i])
  i = i + 1
}

```

Error Message:
The error occurs on line 2: "Kin Error: Unhandled: undefined".

Context:
I am trying to implement merge sort in Kin Lang. The error seems to be related to the array slicing or loop conditions. Any guidance or fixes would be appreciated.

**Comment by pacifiquem** [comment]
There're issues in the way Kin handles errors.... lemme check it :+1+

**Comment by pacifiquem** [comment]
This is the error that you've.

![Screenshot 2024-05-16 104123](https://github.com/kin-lang/kin/assets/96472682/a15dc8be-3271-4576-ac3a-6be1c0d010c3)

**Comment by pacifiquem** [comment]
There have been an issue with how Kin handles errors as communicated early, this is fixed for now and those fixes will appear in `@kin-lang/kin - v0.3.0` which will be released later this week

**Comment by pacifiquem** [comment]
> This is the error that you've.
> 
> ![Screenshot 2024-05-16 104123](https://private-user-images.githubusercontent.com/96472682/331120896-a15dc8be-3271-4576-ac3a-6be1c0d010c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDk0MjQsIm5iZiI6MTcxNTg0OTEyNCwicGF0aCI6Ii85NjQ3MjY4Mi8zMzExMjA4OTYtYTE1ZGM4YmUtMzI3MS00NTc2LWFjM2EtNmJlMWMwZDAxMGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4NDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTdlOTcyOTdiYmYwZDYwMWIwM2E5YmU2ZjIxZjNhN2ViMTRjMzZkMGYwZjIwYzUxNDdjYjE1Yzg5NWZjZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OOUS6-_dFvQ4RyA-STWtduQVXigDVnejvu5CAA5dvfA)

In Kin we don't use `garura` we use `tanga`.

**Comment by MicoDan** [comment]
Okay, got it, thank you very much.
