### ISSUE TITLE
[ERROR] : Module not found when running `kin --version`

### ISSUE THREAD

**Issue by rutaganda-salim** [kin-lang/kin#157]

**Comment by pacifiquem** [comment]
@rutaganda-salim run `kin --version` not *kit --version* and let me know if this is fixed!

**Comment by rutaganda-salim** [comment]
npm i -g @kin-lang/kin 
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Zero-Brainer\\AppData\\Roaming\\npm\\node_modules\\@kin-lang\\kin',  
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Zero-Brainer\AppData\Roaming\npm\node_modules\@kin-lang\kin\node_modules'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Zero-Brainer\\AppData\\Roaming\\npm\\node_modules\\@kin-lang\\kin\\node_modules'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code EEXIST
npm error path C:\Users\Zero-Brainer\AppData\Roaming\npm\kin
npm error EEXIST: file already exists
npm error File exists: C:\Users\Zero-Brainer\AppData\Roaming\npm\kin
npm error Remove the existing file and try again, or run npm
npm error with --force to overwrite files recklessly.

npm error A complete log of this run can be found in: C:\Users\Zero-Brainer\AppData\Local\npm-cache\_logs\2024-07-30T13_14_21_826Z-debug-0.log

**Comment by rutaganda-salim** [comment]
npm i -g @kin-lang/kin 
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Zero-Brainer\\AppData\\Roaming\\npm\\node_modules\\@kin-lang\\kin',  
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Zero-Brainer\AppData\Roaming\npm\node_modules\@kin-lang\kin\node_modules'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Zero-Brainer\\AppData\\Roaming\\npm\\node_modules\\@kin-lang\\kin\\node_modules'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code EEXIST
npm error path C:\Users\Zero-Brainer\AppData\Roaming\npm\kin
npm error EEXIST: file already exists
npm error File exists: C:\Users\Zero-Brainer\AppData\Roaming\npm\kin
npm error Remove the existing file and try again, or run npm
npm error with --force to overwrite files recklessly.

npm error A complete log of this run can be found in: C:\Users\Zero-Brainer\AppData\Local\npm-cache\_logs\2024-07-30T13_14_21_826Z-debug-0.log

**Comment by pacifiquem** [comment]
Try either cleaning cashe by runnging: `npm cache clean --force` or
Force install the package: `npm i -g @kin-lang/kin --force`

Notice that we're using --force on both commands, do this cautiously

**Comment by rutaganda-salim** [comment]
Fixed!

**Comment by pacifiquem** [comment]
Remember to share with us whatever you did with Kin, use this repo [kin showcase](https://github.com/kin-lang/showcase)
