### ISSUE TITLE
[Error] : `KIN_AMAGAMBO.ingano()` method.

### ISSUE THREAD

**Issue by FADHILI-Josue** [kin-lang/kin#40]
**Describe the bug**
issue when using the KIN_AMAGAMBO  ingano method getting error (Error reading file: Cannot read properties of undefined (reading 'type'))

**To Reproduce**
1. make file try.kin
2. add codes ```
      tangaza_amakuru(KIN_AMAGAMBO.ingano("hello"))```
3. run `kin run ./try.kin`
5. See error

**Expected behavior**
could get 5 as result

**Screenshots**
<img width="952" alt="image" src="https://github.com/kin-lang/kin/assets/117774073/6e692e78-a01d-44bf-95d8-c5e6a26fa16c">

**Comment by pacifiquem** [comment]
This method was documented but not yet implemented, it was in TODO!!
We'll work on it.
